name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build template processor Docker image
      run: docker build --tag hh-templates --file Dockerfile .
    - name: Build template test automation Docker image
      run: docker build --tag hh-templates-test --file test/Dockerfile test
    - name: Run tests
      run: docker run --network none --name hh-templates-test --tty hh-templates-test | tee test-log.txt
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      with:
        name: test-log.txt
        path: test-log.txt
    - name: Copy test cases from container
      run: docker cp hh-templates-test:/appdata/cases test_cases
    - name: Upload test cases
      uses: actions/upload-artifact@v1
      with:
        name: test_cases
        path: test_cases
