name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build template processor Docker image
      run: docker build -t hhtemplate -f Dockerfile .
    - name: Build template test automation Docker image
      run: docker build -t hhtemplatetest -f test/Dockerfile test
    - name: Run tests
      run: docker run --rm -t hhtemplatetest | tee test-log.txt
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      with:
        name: test-log.txt
        path: test-log.txt
